# ハッカソンイベント「Open Hack U 2024 TOKYO VOL.2」に参加した話

### 話す人
てつ：コンピューターハード・ソフトを担当

みかど：機械部分と材料加工、本記事の執筆を担当


### 「Open Hack U 2024 TOKYO VOL.2」に参加してきました！

**みかど**先日、ハッカソンイベント、Hack UにPim部内から３人で参加しました

- ハッカソンとは

>ハッカソン（英語: hackathon）とは、ソフトウェア開発分野のプログラマやグラフィックデザイナー、ユーザインタフェース設計者、プロジェクトマネージャらが集中的に作業をするソフトウェア関連プロジェクトのイベントである[1]。個人ごとに作業する場合、班ごとに作業する場合、全体で一つの目標に作業する場合などがある。時にはハードウェアコンポーネントを扱うこともある。ハッカソンは1日から一週間の期間で開催することがある。

“ハッカソン”. ウィキペディア日本語版. 2024-10-14. https://ja.wikipedia.org/w/index.php?title=%E3%83%8F%E3%83%83%E3%82%AB%E3%82%BD%E3%83%B3&oldid=102209626, (参照 2024-12-13).

- 今回参加したハッカソンイベント「Open Hack U」とは
>LINEヤフーが主催する「Hack U」は、LINEヤフー社員のサポートのもと、限られた期間の中で学生がプロダクトを自ら企画・開発・発表するイベントです。

“Open Hack U 2024 [LINEヤフー主催 学生向け開発イベント] - LINEヤフー株式会社”. Hack U - Yahoo! JAPAN. https://hacku.yahoo.co.jp/2024/, (参照 2024-12-13).


**てつ**　で、今回はそのうちの二人で、まぁ

**みかど**　後日談というか。まず、どんなものを作ったか紹介しましょう。まーくすりー？対置き引き上肢検出型カバンまーくすりー？！

**てつ**　３？４だね。

- 対置き引き上肢検出型カバンMKDelta　（Deltaと書いてfourと読む）
置き引き対策がテーマのカバン。取っ手をつかもうとすると取っ手が逃げる。さらに取っ手をつかんでも取っ手が抜けてしまい、ブザーが鳴る。

カバン底面に設置されたWebカメラがカバン上部のスリットを通して上部の状態を確認。取っ手は無限軌道の要領で設置されたベルトに固定されており、ステッピングモーターでベルトを動かし移動させる。「カメラの視野を確保するためにカバン内部には物を入れる事が出来ない」というオチがある。

##### 話題その１：制作物のアイデアはどのように出したのか

**みかど**　帰省するときに新幹線に乗ってた。そん中で、トイレ行くときに置き引き怖いなって話から「置き引き対策のカバンとか作れないかな」っていう話で。多分、おれが取っ手が抜けちゃうカバン……所有者じゃない人が持つと取っ手が抜ける  みたいなのを言い出した気が。

**てつ**  私が、「固定の方が良くない？」って言ったんだけどそれ、ロマンが無いよねってなって、最終的に取っ手がぐにゃぐにゃ逃げちゃえばおもしろいんじゃね？みたいな感じに派生して……

##### 話題その２：開発計画
**みかど**　どんな感じで計画立てたっけ？

- 開発計画と実際の進行
台風の影響でonline開催への変更がなされた。結果的に島根東京間の移動時間を開発にあてる事が出来、当日の朝方に完成した。


**てつ**　なんか、アバウトだったよね。なんか、何日間はハードに使って、何日間をソフトに使うみたいな。

**みかど**　ハードとソフト同時並行でやらなきゃだめだとか、いろいろ思ったんだけど、結局、よくわからない予定を立てて結局機能しなかった……それで我々二人が計画全無視してやるっていう（笑）。

**てつ**　やってたねー（笑）。

**てつ**　結局ハードが出来ないとソフトが出来ないのは正しいんだけど、だからといってじゃあ全員がハードに取り組めますかといったらそうではなかった。だから、ソフト書いている時のハードの人の役割とか……（決めておいた方が）良かった感じはするね。

**みかど**　俺が、出来る技術としてはハードウェア寄りだった事とソフトウェア出来るのがてつ君しかいなかったっていう事で……分業は決定してた事だから平行してやっても良かった。

**てつ**　結局（仕様を）決定したのは私だったから。ハードもソフトも全部やっちゃったっていう（笑）。普通にソフト担当の人間の立ち回りとしてハード側の仕事にも関われたのは割と時間的にはロスが少なくなって良かったのかなと思って……

**みかど**　コンピュータ、ハードもソフトも全部お願いしちゃった感じだったね
俺が機械か。

**てつ**　機械とあと加工ね。加工は全部やってもらったから。機構を作るのをやってもらったね。開発期間が短いから買ってから届くまでに時間がかかって、間に合わないよねって。それで結局使える機構が少なくなっちゃった感じはある。

**みかど**　地方に住んでいるっと計画は色々考えないといけなかったね。計画なしで何とかなってしまったけど本当は良くない

**てつ**　何とかなっ……まーね。

**みかど**　計画でさ、デバッグ作業1日みたいな計画だったよね

**てつ**　あれ頭おかしくてさ、デバッグやりながら機構を改造して、とかが必要で……１週間でデバッグと機構の見直しとを交互にやっていく方が良かった説はあるね。

**みかど**　やっぱ機関が短い以上、試行錯誤せざるを得ないから。そういうところを考えると最後の調整みたいなところに時間を割くべきだったんだろうなと思った。

**てつ**　ロボット工学やってた時に、詰めの調整が１番だるくて時間かかったんだよね。物が出来てから勝負だったりする。

**みかど**　他の人たちはソフトウェアとか作ってたけど、うちのチームはハードウェアもあったから。こっちは結構泥臭い調整とかも必要だったりする訳だから。

**てつ**　ソフトも割とデバッグだるいけどね。

**みかど**　だってさ、こっちはプログラムちゃんと書いてても動かない事あるでしょ？

**てつ**　あったね、電圧降下とかね。あれも考慮してたら……。考慮する以前に発生したときにコントリビューターの人に「どうしたらいいですか」って聞く猶予すらなかったから、

**みかど**　向こうの社員さんのサポートの体制もあったけど活用できないくらいスケジュール的に、

**てつ**　おかしかったもんね。現物出来たの発表の日の朝だった。最後の日は寝てないね。

##### 話題その３：開発で詰まったポイント
**みかど**　詰まったポイントは個人によって違うけど、

**てつ**　逆に聞くが、どこで詰まった？

**みかど**　最終的な機械部分の調整……ソフトウェアが出来てるのに変な動きする！みたいなのを修正しないといけなかったから、そこが詰まったといえるのか？作り始めてからはなんだかんだでそんなに障害はなかったね

**てつ**　ソフトウェア的には詰まったことだらけで、もともとM5スタックを使おうと思ってたんだけど、ファームウェアがうまく焼けないどころか開発環境すらどれ使ったら良いのかって……しかもどれやってもうまくいかなくて……ほんとに詰みだなって思ってた。ラズベリーパイ使いなよって言ってくれた人がいたので（なんとかなった）。サーバーの業務とかでUbuntuServer触ってたから、応用できる知識があってなんとか助かったっていうのはすごく大きかった。あと、超音波式のセンサーを使う話があったんだけど、それの通信形式がI2CでM5StackだとI2C使えるんだけど、ラズベリーパイだと

**みかど**間になんか

**てつ**そう、ライブラリーがクソめんどくさくて。そこも方式変えてOpenCV使ってWebカメラの画像を取得してきてって、でっけー変更もあったし、結構もともとの計画から変えないといけない事情が多数あったのが非常にでかい。

**みかど**あと俺詰まったの思い出した。俺、発表したんだ。

**てつ**　（笑）　

**みかど**発表がめっちゃ詰まった気がする。当日９時とかにzoomでつないで開会式みたいなのがあって、

**てつ**　朝６時くらいに現物が完成して、そこから２人で動画撮ったりなんなりして資料作って、動画撮ってる途中で電池の電圧が下がっちゃって全然動かなくなっちゃって、急いでスーパーに９v電池買いに行って……


**みかど**そこも詰まったし、（発表開始時に）間違えてzoomから抜けちゃったんだ。

**てつ**でも（再接続してから）急いでしゃべって間に合わすっていうね。

**みかど**早口過ぎて時間余らせちゃったっていう（笑）。発表の準備が不十分だったっていうのはある。

##### 話題その４：開発中の最も大きな出来事

**みかど**　転換点みたいなのはあったよね。

**てつ**　だね。仕組みを抜本的に変えちゃったっていうのがやっぱりでかかったのかな。

**みかど**　超音波のセンサーからWebカメラで手を認識するっていう変更、

**てつ**　あれね、実はね手、認識してないんだ（笑）。色の差分を取ってやってるだけなんだけど。

**みかど**　そっかそっか。

**てつ**I2Cが本当に苦行だったから。電子部品のプログラムって本当にめんどくさいんだなって。今やろうとしている方向性に対して批判的に評価出来る人間がいた方が良かったってすごく思う。

**みかど**　２人じゃしょうがない（笑）

**てつ**２人じゃしょうがないし、全体像を構想できる人間が私しかいなかったからね。

##### 話題その５：あの日々に戻ったなら

**てつ**　うーん……とりあえずさっさと現物作っちゃう。アイデアでた時点でふわっとした物じゃなくて設計図をガチガチに書いちゃうぐらいに設計しといた方がいいよね。最初の１日２日でそれやっちゃって、

**みかど**　（試作品を）１個くらい作っちゃっても良かったんじゃないかな。お金が無かったけど。

**てつ**　だね。（お金が）たくさんあるから出来るよ、みたいな環境ではなかった。

**みかど**　自費だからね。敷金礼金アタックでアパートのカーテンレール引っぺがして使うみたいな案が出るくらいにはお金がなかった。

##### 話題その６：ハッカソンに参加するべきあか（ハッカソンへの参加をためらっている人を後押ししたい）

**みかど**　まぁ結果的に良い経験になったから参加するべきだよね。

**てつ**　学ぶことは非常に多かったよね。縛られてる状況で何かを成し遂げようとするって非常に難しい事だから、やってみると見る世界が一つ広がるのかなとは思う。

**みかど**　良いアウトプットの場にはなると思う。いつもインプットだけになりがちなだから。入賞とかにかすんなかったのが1番納得いかない

**てつ**　みんなハッカソンとして一番面白いとは言ってくれたけどね。ちょっとね完成度が低かったというか、トロ過ぎて逃げてないというか。もっと技術を馬鹿みたいに投入した無駄遣いを出来たらよかったかなっていう。時間あったら、別の方式もできたしソフトの制御的にも……

……（改善案について語るてつ）

だからステッピングモーターを使う必要さえなかったじゃん。そういう頭の良い回答を一切できなかったのが良くなかったのかな。

##### 話題その７：最後に今後ハッカソンに参加する人へ一言

**てつ**まぁもまれてみないと分からんから頑張れとしか。「制約がある中での開発ってどんな困難があるの？」、「何を意識したらいいの？」みたいなのを知る事は出来ると思うから。

**みかど**　他のチームを見て思ったけど、「まだできてません」みたいなのあったよね。

**てつ**　平気であった。

**みかど**　全然失敗してもいいんだなって。

**てつ**　賞取らなくてもいいから、自分の手を動かして一回作ってみるってのはすごい大事かもしれないね。

~~END~~